unbind C-b
set -g prefix C-s

unbind r
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-interval 1
set -g status-justify centre # center align window list

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

set-option -g mouse on

set-option -g renumber-windows on

set-option -g history-limit 1000000

# Use | for vertical splitting and - for horizontal
bind-key v split-window -h -c '#{pane_current_path}'
bind-key | split-window -h -c '#{pane_current_path}'
bind-key s split-window -c '#{pane_current_path}'
bind-key - split-window -c '#{pane_current_path}'
unbind '"'
unbind %

bind c new-window -c '#{pane_current_path}'

# bind-key -n C-o send-keys -R
# bind-key -n C-o clear-history

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Other examples:
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "nordtheme/tmux"
# set -g @plugin 'fabioluciano/tmux-tokyo-night'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
